USE TESTING_SYSTEM_ASSIGNMENT_1;

-- Question 1: Tạo view có chứa danh sách nhân viên thuộc phòng ban sale
CREATE VIEW W_DEPARTMENT_NAME AS
     SELECT A.EMAIL,A.USERNAME,A.FULL_NAME FROM  `ACCOUNT` A
         JOIN DEPARTMENT D
		 ON D.DEPARTMENT_ID=A.DEPARTMENT_ID
         WHERE D.DEPARTMENT_NAME = ' SALE ';
 SELECT * FROM  W_DEPARTMENT_NAME  ;
 
 -- Question 2: Tạo view có chứa thông tin các account tham gia vào nhiều group nhất
 CREATE VIEW W_GROUP_ACCOUNT_DSVN  AS
   SELECT A.EMAIL,A.USERNAME,A.FULL_NAME,A.ACCOUNT_ID,COUNT(GA.ACCOUNT_ID) FROM `ACCOUNT` A
    JOIN GROUP_ACCOUNT GA
    ON A.ACCOUNT_ID = GA.ACCOUNT_ID
    GROUP BY A.ACCOUNT_ID
    HAVING COUNT(GA.ACCOUNT_ID) =
      (SELECT MAX(TABLEA) FROM 
		   (SELECT COUNT(ACCOUNT_ID) AS TABLEA FROM `ACCOUNT` GROUP BY ACCOUNT_ID) AS TABLEB);
  
  SELECT * FROM W_GROUP_ACCOUNT_DSVN;
  
  -- Question 3: Tạo view có chứa câu hỏi có những content quá dài (content quá 300 từ được coi là quá dài) và xóa nó đi
  
  CREATE VIEW W_QUESTION_MAXCONTENT  AS
     SELECT * FROM  QUESTION  WHERE LENGTH(CONTENT) >=300;
  DELETE FROM  W_QUESTION_MAXCONTENT;
     
 
-- Question 4: Tạo view có chứa danh sách các phòng ban có nhiều nhân viên nhất
  CREATE OR REPLACE VIEW W_ACCOUNT_MAXNV  AS
          SELECT COUNT(A.DEPARTMENT_ID),D.DEPARTMENT_NAME,A.EMAIL,A.USERNAME,A.FULL_NAME FROM DEPARTMENT D
            JOIN `ACCOUNT` A 
			ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
            GROUP BY A.DEPARTMENT_ID
            HAVING COUNT(A.DEPARTMENT_ID)=
                 (SELECT MAX(TABLEA) FROM 
		           (SELECT COUNT(ACCOUNT_ID) AS TABLEA FROM `ACCOUNT` GROUP BY ACCOUNT_ID) AS TABLEB);

 SELECT * FROM W_ACCOUNT_MAXNV; 

--   Question 5: Tạo view có chứa tất các các câu hỏi do user họ Nguyễn tạo		
CREATE OR REPLACE VIEW W_CREATOR_BY_NGUYEN  AS
SELECT A.FULL_NAME,A.USERNAME FROM QUESTION Q
   RIGHT JOIN `ACCOUNT` A
   ON Q.CREATOR_ID = A.ACCOUNT_ID
   WHERE A.FULL_NAME LIKE 'NGUYỄN%';

 SELECT * FROM    W_CREATOR_BY_NGUYEN
